In [1]:
import pandas as pd

In [2]:
a = pd.read_csv("/home/ubuntu/giodir/digitalPathology/data/alice/master_patch_table_cleaned.csv")

In [3]:
a.head()

,image,bag_id,patch_path,label,n_cells,area_mean,area_std,area_median,perimeter_mean,perimeter_std,...,intensity_mean_median,intensity_min_mean,intensity_min_std,intensity_min_median,intensity_max_mean,intensity_max_std,intensity_max_median,intensity_std_mean,intensity_std_std,intensity_std_median
0,RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_134946_p...,RE_I_25_16291_1_I,bag/RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_1349...,0,50,158.940000,134.789391,112.5,46.526930,21.254300,...,-0.145111,-0.850516,0.502908,-0.799768,0.720202,0.232821,0.759531,0.323813,0.153785,0.286539
1,RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_134946_p...,RE_I_25_16291_1_I,bag/RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_1349...,0,47,175.382979,105.173677,154.0,50.709004,17.390671,...,-0.370591,-0.801830,0.359094,-0.908291,0.514689,0.213103,0.526161,0.284303,0.106804,0.293826
2,RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_134946_p...,RE_I_25_16291_1_I,bag/RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_1349...,0,55,164.563636,123.327292,134.0,48.862360,20.762797,...,-0.022011,-0.699869,0.412104,-0.697085,0.664233,0.229779,0.693572,0.285140,0.150035,0.244039
3,RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_134946_p...,RE_I_25_16291_1_I,bag/RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_1349...,0,54,172.796296,136.612712,139.0,48.451220,21.635252,...,-0.010690,-0.542744,0.333777,-0.501831,0.572330,0.241291,0.544881,0.222378,0.101055,0.213193
4,RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_134946_p...,RE_I_25_16291_1_I,bag/RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_1349...,0,37,152.945946,87.897019,144.0,48.266463,15.247424,...,-0.398489,-0.838045,0.391354,-0.925830,0.463120,0.222736,0.473210,0.295447,0.122540,0.310477

In [4]:
a_lim = a.head()

In [5]:
a_lim

,image,bag_id,patch_path,label,n_cells,area_mean,area_std,area_median,perimeter_mean,perimeter_std,...,intensity_mean_median,intensity_min_mean,intensity_min_std,intensity_min_median,intensity_max_mean,intensity_max_std,intensity_max_median,intensity_std_mean,intensity_std_std,intensity_std_median
0,RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_134946_p...,RE_I_25_16291_1_I,bag/RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_1349...,0,50,158.940000,134.789391,112.5,46.526930,21.254300,...,-0.145111,-0.850516,0.502908,-0.799768,0.720202,0.232821,0.759531,0.323813,0.153785,0.286539
1,RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_134946_p...,RE_I_25_16291_1_I,bag/RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_1349...,0,47,175.382979,105.173677,154.0,50.709004,17.390671,...,-0.370591,-0.801830,0.359094,-0.908291,0.514689,0.213103,0.526161,0.284303,0.106804,0.293826
2,RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_134946_p...,RE_I_25_16291_1_I,bag/RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_1349...,0,55,164.563636,123.327292,134.0,48.862360,20.762797,...,-0.022011,-0.699869,0.412104,-0.697085,0.664233,0.229779,0.693572,0.285140,0.150035,0.244039
3,RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_134946_p...,RE_I_25_16291_1_I,bag/RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_1349...,0,54,172.796296,136.612712,139.0,48.451220,21.635252,...,-0.010690,-0.542744,0.333777,-0.501831,0.572330,0.241291,0.544881,0.222378,0.101055,0.213193
4,RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_134946_p...,RE_I_25_16291_1_I,bag/RE_I_25_16291_1_I/RE-I_25_16291_1_I_1_1349...,0,37,152.945946,87.897019,144.0,48.266463,15.247424,...,-0.398489,-0.838045,0.391354,-0.925830,0.463120,0.222736,0.473210,0.295447,0.122540,0.310477